---
youji:
    muc:
        rejoin:
            interval: 4000
            maxinterval: 10000
    initial-accounts:
        - "youji_sagan:BNasdfhk87623#@draugr.de/hooita"
        - "youji_sagan1:BNasdfhk87623#@draugr.de/hooita"
    db:
        logs: !url  http://ya.ru

jvm.properties:
    logback.configurationFile : conf/logback.xml
    # tree-like structures are also allowed
    smack:
        debugEnabled: true
