---
initial-accounts:
    - "youji00:qazxsw#@draugr.de/hooita"
    - "youji01:qazxsw#@draugr.de/hooita"
    #- "youji_sagan:BNasdfhk87623#@draugr.de/hooita"
    #- "youji_sagan1:BNasdfhk87623#@draugr.de/hooita"
